### ISSUE TITLE
'pyomo.core.base' has no attribute 'expr coopr3"

### ISSUE THREAD

**Issue by kororiev** [Pyomo/pyomo#1673] opened 2020-10-21 14:00 UTC
Hi there. I'm trying to solve a power system model on pypsa (0.17.1) with pyomo (5.7.1). 
When running the code on jupyter notebook, I get the following error: 
>module 'pyomo.core.base' has no attribute 'expr_coopr3'

Just before that, the code tried to execute the following line from pypsa: 
> v._data[i]._body = pyomo.core.base.expr_coopr3._SumExpression()

Any idea what is the problem and how to solve it? (I'm using Python 3.8.5). 
Cheers

**Comment by blnicho** [comment] 2020-10-21 14:58
@kororiev it looks like the notebook you're using has an outdated reference to `expr_coopr3`. I'm pretty sure this was removed in the Pyomo expression system rewrite that was merged in #524 a couple years ago. I can't find any reference to `expr_coopr3` in the PyPSA code so I'm guessing the issue is coming from your notebook. Could you post a minimal example that recreates the error you're seeing?

**Comment by kororiev** [comment] 2020-10-21 16:10
Thanks Bethany for the quick reply!

In short, my code is as follow:

I defined first a build_model function

   def build_model (co2price=0, data=data, uc_run=False)

I use this function to create an instance of the pypsa.Network class

   network = build_model(co2price=0, data=data, uc_run=False)

Then I run the pypsa solver lopf method

   network.lopf(solver_name="cbc")



No problem in building the model. but then I get the following cascade of
errors:



~\Anaconda3\lib\site-packages\pypsa\opf.py in network_lopf(network,
snapshots, solver_name, solver_io, skip_pre, extra_functionality,
solver_options, keep_files, formulation, ptdf_tolerance, free_memory)

-> 1517     network_lopf_build_model(network, snapshots, skip_pre=skip_pre,



~\Anaconda3\lib\site-packages\pypsa\opf.py in
network_lopf_build_model(network, snapshots, skip_pre, formulation,
ptdf_tolerance)

-> 1345     define_generator_variables_constraints(network,snapshots)



~\Anaconda3\lib\site-packages\pypsa\opf.py in
define_generator_variables_constraints(network, snapshots)

--> 300     l_constraint(network.model, "ramp_up", ru, list(ru_gens),
snapshots[1:])



~\Anaconda3\lib\site-packages\pypsa\opt.py in l_constraint(model,
name, constraints, *args)

--> 204         v._data[i]._body = pyomo.core.base.expr_coopr3._SumExpression()



AttributeError: module 'pyomo.core.base' has no attribute 'expr_coopr3'





There is no explicit reference to coopr3 in my script. I guess the
inconsistency may be somewhere in the libraries I’m calling (but I’m using
the latest version of all of them). Do you mean that an outdated version of
jupyter notebook could also mess things up?

In any case, if you have any inspirational thoughts on that, be my guest!
Cheers.

**Comment by emma58** [comment] 2020-10-21 17:03
@kororiev, this seems related to PyPSA/PyPSA#190. I think it may be an issue for pypsa.

**Comment by emma58** [comment] 2020-11-17 20:06
Closing this as it does not seem to be an issue with Pyomo.

**Closed by emma58** 2020-11-17 20:06 UTC
Labels: question
