### ISSUE TITLE
5.6.2 GAMS writer probelm: AttributeError: '_GeneralExpressionData' object has no attribute '_associativity'

### ISSUE THREAD

**Issue by natalieisenberg** [Pyomo/pyomo#1029] opened 2019-05-23 16:56 UTC
I have noticed that for the same Pyomo model, using the GAMS writer in Pyomo 5.6.2 gives this error:

 AttributeError: '_GeneralExpressionData' object has no attribute '_associativity'

Which I believe is being raised in the gams_writer.py "visit" function. I do not get this error with Pyomo 5.6.1 for that same model.

**Comment by blnicho** [comment] 2019-05-23 17:23
Do you have a small example you can share that recreates this behavior?

**Comment by natalieisenberg** [comment] 2019-05-23 18:37
I can try to make a simple example! But it may take some trial-and-error.

**Comment by jsiirola** [comment] 2019-05-23 18:42
I believe it is caused by a model with an `Expression` component in it.  PR #1031 should fix that specific issue.

**Comment by blnicho** [comment] 2019-05-23 18:43
Looks like @jsiirola tracked down the problem already so don't worry about an example. We should have a fix merged shortly and we'll be cutting a patch release tomorrow.

**Closed** 2019-05-23 21:36 UTC
