### ISSUE TITLE
DAE Error

### ISSUE THREAD

**Issue by mharyoowa** [Pyomo/pyomo#2307] opened 2022-02-23 17:39 UTC
## Summary
Trying to solve a DAE problem using the Coolocation Transformation Discretization method. I keep getting an Attribute Error.

### Steps to reproduce the issue

```console
$ command1 [options]
# import the neeeded packages/libraries
from pyomo.environ import *
from pyomo.dae import *
import numpy as np
from math import pi

# Define the model
model = ConcreteModel()

# Parameters provided
k1 = 5.0 / 6.0     # min^-1
k2 = 5.0 / 3.0     # min^-1
k3 = 1.0 / 6000    # m^3/(gmol min)
caf = 10000.0      # gmol/m^3

# define the Parameters and ContinuousSet
model.k1 = Param(initialize = k1)
model.k2 = Param(initialize = k2)
model.k3 = Param(initialize = k3)
model.caf = Param(initialize = caf)
model.t = ContinuousSet(bounds=(0, 1))

# define the variables
model.sv = Var(model.t, initialize = 1.0, within=PositiveReals)
model.ca = Var(model.t, initialize = 5000.0, within=PositiveReals)
model.cb = Var(model.t, initialize = 2000.0, within=PositiveReals)
model.cc = Var(model.t, initialize = 2000.0, within=PositiveReals)
model.cd = Var(model.t, initialize = 1000.0, within=PositiveReals)

# define the Derivative Variables
model.dcadt = DerivativeVar(model.ca, wrt=model.t)
model.dcbdt = DerivativeVar(model.cb, wrt=model.t)
model.dccdt = DerivativeVar(model.cc, wrt=model.t)
model.dcddt = DerivativeVar(model.cd, wrt=model.t)
$ command2 [options]
# Define the Objective
def objec(model):
    return model.cb
model.obj = Objective(rule=objec, sense=maximize)

# formulate the differential equations using standard Pyomo Constraints
def ca_bal(model, t):
    return model.dcadt[t] == model.sv[t] * caf - model.sv[t] * model.ca[t] - k1 * model.ca[t] - 2.0 * k3 * model.ca[t] ** 2.0
model.ca_bal = Constraint(model.t, rule=ca_bal)

def cb_bal(model, t):
    return model.dcbdt[t] == -model.sv[t] * model.cb[t] + k1 * model.ca[t] - k2 * model.cb[t]
model.cb_bal = Constraint(model.t, rule = cb_bal)

def cc_bal(model, t):
    return model.dccdt[t] ==  -model.sv[t] * model.cc[t] + k2 * model.cb[t]
model.cc_bal = Constraint(model.t, rule = cc_bal)

def cd_bal(model, t):
    return model.dcddt[t] ==  -model.sv[t] * model.cd[t] + k3 * model.ca[t] ** 2.0
model.cd_bal = Constraint(model.t, rule=cd_bal)

# Speicfy the initial or boundary conditions
def _init(model):
    yield model.ca[0] == 0
    yield model.cb[0] == -1
    yield model.cc[0] == 0
    yield model.cd[0] == 0
model.init_conditions = ConstraintList(rule=_init)

# Discretize model using radau collocation
discretizer = TransformationFactory('dae.collocation')
discretizer.apply_to(model,nfe=7,ncp=6,scheme='LAGRANGE-RADAU')

# Solve algebraic model
opt = SolverFactory('ipopt')
results = opt.solve(model, tee=True)
```

```
# example.py
import pyomo.environ
...
```

### Error Message
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_16528/2025479577.py in <module>
      5 # Solve algebraic model
      6 opt = SolverFactory('ipopt')
----> 7 results = opt.solve(model, tee=True)

~\Anaconda5\lib\site-packages\pyomo\opt\base\solvers.py in solve(self, *args, **kwds)
    567             initial_time = time.time()
    568 
--> 569             self._presolve(*args, **kwds)
    570 
    571             presolve_completion_time = time.time()

~\Anaconda5\lib\site-packages\pyomo\opt\solver\shellcmd.py in _presolve(self, *args, **kwds)
    203         self._define_signal_handlers = kwds.pop('use_signal_handling',None)
    204 
--> 205         OptSolver._presolve(self, *args, **kwds)
    206 
    207         #

~\Anaconda5\lib\site-packages\pyomo\opt\base\solvers.py in _presolve(self, *args, **kwds)
    664             write_start_time = time.time()
    665             (self._problem_files, self._problem_format, self._smap_id) = \
--> 666                 self._convert_problem(args,
    667                                       self._problem_format,
    668                                       self._valid_problem_formats,

~\Anaconda5\lib\site-packages\pyomo\opt\base\solvers.py in _convert_problem(self, args, problem_format, valid_problem_formats, **kwds)
    715                          valid_problem_formats,
    716                          **kwds):
--> 717         return convert_problem(args,
    718                                problem_format,
    719                                valid_problem_formats,

~\Anaconda5\lib\site-packages\pyomo\opt\base\convert.py in convert_problem(args, target_problem_type, valid_problem_types, has_capability, **kwds)
     98                     tmpkw = kwds
     99                     tmpkw['capabilities'] = has_capability
--> 100                     problem_files, symbol_map = converter.apply(*tmp, **tmpkw)
    101                     return problem_files, ptype, symbol_map
    102 

~\Anaconda5\lib\site-packages\pyomo\solvers\plugins\converter\model.py in apply(self, *args, **kwds)
    178                 else:
    179                     (problem_filename, symbol_map_id) = \
--> 180                         instance.write(
    181                             filename=problem_filename,
    182                             format=args[1],

~\Anaconda5\lib\site-packages\pyomo\core\base\block.py in write(self, filename, format, solver_capability, io_options)
   1820         if solver_capability is None:
   1821             def solver_capability(x): return True
-> 1822         (filename, smap) = problem_writer(self,
   1823                                           filename,
   1824                                           solver_capability,

pyomo\repn\plugins\ampl\ampl_.pyx in pyomo.repn.plugins.ampl.ampl_.ProblemWriter_nl.__call__()

pyomo\repn\plugins\ampl\ampl_.pyx in pyomo.repn.plugins.ampl.ampl_.ProblemWriter_nl.__call__()

pyomo\repn\plugins\ampl\ampl_.pyx in pyomo.repn.plugins.ampl.ampl_.ProblemWriter_nl.__call__()

pyomo\repn\plugins\ampl\ampl_.pyx in pyomo.repn.plugins.ampl.ampl_.ProblemWriter_nl._print_model_NL()

pyomo\repn\standard_repn.pyx in pyomo.repn.standard_repn.generate_standard_repn()

AttributeError: 'IndexedVar' object has no attribute 'is_potentially_variable'

```console
$ # Output message here, including entire stack trace, if available
```

### Information on your system

Pyomo version: latest version
Python version: 3.10
Operating system:  Windows 11
How Pyomo was installed (PyPI, conda, source): conda
Solver (if applicable): ipopt, glpk

**Comment by blnicho** [comment] 2022-02-23 18:29
@mharyoowa the problem is in your objective function. You need to provide a time index for `model.cb`. It's unfortunate that the error message isn't more helpful in identifying the problem but I think that is a separate issue so I'm going to close this.

**Closed by blnicho** 2022-02-23 18:29 UTC
Labels: bug
