### ISSUE TITLE
Is Pyomo able to do parallel optimization?

### ISSUE THREAD

**Issue by erikfilias** [Pyomo/pyomo#1196] opened 2019-11-21 11:33 UTC
Hi All,

I am relatively new in Pyomoa. I work with large scale models (solving several linear programming models with more than 10000+ variables and 10000+ constraints) in GAMS. Fortunately, there are some tools for parallel computing in GAMS as I show below that I use in order to increase the performance.

a. The Grid and Multi-Threading Solve Facility.
https://www.gams.com/latest/docs/UG_GridComputing.html
b. The Gather-Update-Solve-Scatter (GUSS).
https://www.gams.com/latest/docs/S_GUSS.html

So, I would like that someone can show me If there any tools like GridComputing and GUSS of GAMS in Pyomo. Even a simple example will be highly apreciated. Thank you so much!

**Comment by gseastream** [comment] 2019-11-23 19:55
I'm not sure if this answers your question, but the [GAMS writer](https://pyomo.readthedocs.io/en/stable/library_reference/solvers/gams.html#gams-writer) does include a parameter called `add_options` which allows you to pass the writer a list of lines to insert right before the solve statement. I don't know anything about the parallel capabilities in GAMS but theoretically you can use this option to put the necessary code into the model file so that it executes when the solver interface runs the file, and assuming it populates the GAMS model with the answers the same way it does in a single-threaded solve then it should work as intended.

The only problem with that right now is there is currently no parameter in the GAMS writer to skip writing the standard solve statement so it would go ahead and run a single-threaded solve right after your custom parallel solve, but that parameter could easily be added if people think it's a good idea.

**Comment by mrmundt** [comment] 2021-04-14 17:44
We have opened #1925 to address this request and will close this issue.

**Closed by mrmundt** 2021-04-14 17:44 UTC
Labels: question
