### ISSUE TITLE
Appveyor tests are always "passing"

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#4] opened 2016-06-08 12:45 UTC
The root cause may be the return value for test.pyomo.exe.  I suspect that it's not returning a nonzero value when a test fails.

**Comment by whart222** [comment] 2016-06-08 12:46
Does anyone have a Windows box that they can test this on?

**Comment by ghackebeil** [comment] 2016-06-27 04:40
Ah, I think I know what the problem is. We are testing Pyomo trunk against the latest PyUtilib _release_. So the various fixes I have been making in PyUtilib that are referenced above are not even being tested on appveyor (or travis).

**Comment by ghackebeil** [comment] 2016-06-27 05:02
It looks like the series of fixes I've made on PyUtilib trunk (starting at https://github.com/PyUtilib/pyutilib/commit/dfa78b4772c83ec4e057c8a43e9765af1670eb27) along with the updates to the appveyor (and travis) script to install PyUtilib trunk (6cc8409c481e1640bda94f7322bd61deca8311d0) have fixed this.

Now we just need to understand why the test script output on appveyor is a few thousand lines of empty space. Something I am going to leave for another day...

**Comment by ghackebeil** [comment] 2016-06-27 06:10
It looks like the tee keyword for pyutilib.subprocess.run has a strange interaction with the appveyor console output. If you look at the raw log file, all of the test output is there. It's just the live output that appveyor is directing to the webpage is nothing bu blank lines.

@jsiirola will have to investigate this further, as I think he has done the most work on output redirection in that function. Also, this should technically be reopened as a pyutilib issue at this point.

**Comment by whart222** [comment] 2016-07-06 20:24
There is a new branch for PyUtilib, issue-22, that is focused on addressing this issues.  Once this branch is resolved, we should generate a new PyUtilib release, which will allow us to close this issue.

**Comment by whart222** [comment] 2018-01-03 15:38
I'll let @jsiirola comment.  I think he fixed the Appveyor tests, but not by fixing the PyUtilib issue-22.  (Right?)

**Comment by jsiirola** [comment] 2018-01-04 22:23
This is definitely fixed for Pyomo.  I will close this issue.

I am not sure on the status of Pyutilib/pyutilib#22.

**Closed by jsiirola** 2018-01-04 22:23 UTC
