### ISSUE TITLE
GAMS writer problem: Unallowable component ContinuousSet

### ISSUE THREAD

**Issue by MAZamarripa** [Pyomo/pyomo#340] opened 2018-02-08 15:20 UTC
1.- When using expressions and exporting the model to GAMS, there are some issues with the final expressions. @jsiirola 
GAMS error: "More than one operator in a row. You need to use parenthesis"
Two examples: 
Y = 4000 + - T + 2000
(2*x)** -0.5
pyomo returns "*** Status: Compilation error(s)" errors from GAMS could be useful to understand the issue.

2.- Importing a model using DAE tools is not working (@blnicho):
RuntimeError: Unallowable component(s) ContinuousSet.
The GAMS writer cannot export models with this component type

Regards,
Miguel

**Comment by qtothec** [comment] 2018-02-08 15:23
1. I've run into this issue before. Do you have a small model that reproduces what happens here? That way @gseastream might be able to take a look.
2. Did you discretize the model first?

**Comment by qtothec** [comment] 2018-02-08 15:24
Related: #306

**Comment by jsiirola** [comment] 2018-02-08 16:20
Part 1 is almost certainly a duplicate of #306. Part 2 is new.  I am re-titling this issue to only track Part 2 (leaving #306 to track part 1).  In the future, please report these as separate issues.

@MAZamarripa: please either attach or point us to an example that reproduces these problems.

**Comment by MAZamarripa** [comment] 2018-02-08 18:16
You can reproduce this issue using the DAE_tutorial.py from your library. 

#  ___________________________________________________________________________
#
#  Pyomo: Python Optimization Modeling Objects
#  Copyright 2017 National Technology and Engineering Solutions of Sandia, LLC
#  Under the terms of Contract DE-NA0003525 with National Technology and 
#  Engineering Solutions of Sandia, LLC, the U.S. Government retains certain 
#  rights in this software.
#  This software is distributed under the 3-clause BSD License.
#  ___________________________________________________________________________

# Example 1 from http://www.mathworks.com/help/matlab/ref/pdepe.html

from pyomo.environ import *
from pyomo.dae import *

m = ConcreteModel()
m.pi = Param(initialize=3.1416)
m.t = ContinuousSet(bounds=(0,2))
m.x = ContinuousSet(bounds=(0,1))
m.u = Var(m.x,m.t)

m.dudx = DerivativeVar(m.u,wrt=m.x)
m.dudx2 = DerivativeVar(m.u,wrt=(m.x,m.x))
m.dudt = DerivativeVar(m.u,wrt=m.t)

def _pde(m,i,j):
    if i == 0 or i == 1 or j == 0 :
        return Constraint.Skip
    return m.pi**2*m.dudt[i,j] == m.dudx2[i,j]
m.pde = Constraint(m.x,m.t,rule=_pde)

def _initcon(m,i):
    if i == 0 or i == 1:
        return Constraint.Skip
    return m.u[i,0] == sin(m.pi*i)
m.initcon = Constraint(m.x,rule=_initcon)

def _lowerbound(m,j):
    return m.u[0,j] == 0
m.lowerbound = Constraint(m.t,rule=_lowerbound)

def _upperbound(m,j):
    return m.pi*exp(-j)+m.dudx[1,j] == 0
m.upperbound = Constraint(m.t,rule=_upperbound)

m.obj = Objective(expr=1)

# Discretize using Orthogonal Collocation
# discretizer = TransformationFactory('dae.collocation')
# discretizer.apply_to(m,nfe=10,ncp=3,wrt=m.x)
# discretizer.apply_to(m,nfe=20,ncp=3,wrt=m.t)

# Discretize using Finite Difference and Collocation
discretizer = TransformationFactory('dae.finite_difference')
discretizer2 = TransformationFactory('dae.collocation')
discretizer.apply_to(m,nfe=25,wrt=m.x,scheme='BACKWARD')
discretizer2.apply_to(m,nfe=20,ncp=3,wrt=m.t)

if __name__ == '__main__':
    '''
    from pyomo.opt import SolverFactory
    import pyomo.environ
    opt=SolverFactory("ipopt")
    results = opt.solve(m)
    #sends results to stdout
    results.write()
    print("\nDisplaying Solutions\n" + "-"*60)
    pyomo_postprocess(None, results)
    '''
    # Send to GAMS
    
    from pyomo.environ import *
    opt=SolverFactory('gams', solver_io='direct')
    io_options = dict()
    io_options['solver'] = "baron"
    io_options['mtype'] ="nlp"
    io_options['symbolic_solver_labels']=True
    
    #m.write('GAMS_file.gms', io_options=io_options)
    results = opt.solve(m)
    #'''

**Comment by blnicho** [comment] 2018-02-08 21:18
The reason this is happening is because `ContinuousSet`s are not being reclassified as `Set`s after a discretization is applied. This was never a problem for the nl writer because it writes expressions and doesn't care about the indexing sets. 

@qtothec or @jsiirola, does the GAMS writer actually write out the indexing sets?

**Comment by jsiirola** [comment] 2018-02-08 21:26
No - but the GAMS writer does do the "correct" thing and complain about ctypes that it doesn't know how to handle (to prevent users from thinking that they are solving a problem, when the solver didn't actually see / understand the whole problem).  In a separate discussion (#309) we are debating what unknown components solvers/writers should complain about.  I am starting to think that only components inheriting from `ActiveComponent` should be a problem, which would argue for updating the GAMS writer to silently ignore `ContinuousSet` components.  But others have voiced concern where there might be good reasons to complain about non-ActiveComponents, too...

Alternatively, the discretizer could reclassify the `ContinuousSet` after discretization.  @blnicho, do you see a problem with reclassification?

**Comment by blnicho** [comment] 2018-02-08 21:48
@jsiirola the reclassification would cause a problem with the Simulator if the model is discretized before simulation (but this discussion has revealed a similar bug with `DerivativeVar` that needs to be resolved). Is there something similar to `component_map` for getting model components back based on their class instead of their type?

**Comment by whart222** [comment] 2018-02-08 21:56
FYI, I know for a fact that the first issue has been resolved on the expr_dev branch.  Yet another reason to merge that ASAP.

**Comment by jsiirola** [comment] 2018-02-08 21:59
@blnicho: Alas, no.  You could iterate through all the `Set`s and check isinstance, but that is IMHO not a good solution.   I think a better place to store that information is in a `ComponentSet` attached to a `_dae_discritization_info` block.

**Comment by blnicho** [comment] 2018-05-22 02:06
@qtothec we already have an open issue tracking the more general case in #309

**Comment by gseastream** [comment] 2018-06-19 22:41
So I realized today that the GAMS writer still does not allow models to have Connectors whether they are expanded or not, and the writer will also not allow ContinuousSets since it's not in the list of valid ctypes. I imagine this issue is still relevant to all the writers since #309 is still open, but I figured we may be able to use the GAMS writer as a starting point to coming to a conclusion on the topic. The discussion in the various issues and PRs about the GAMS writer and Connectors seemed to conclude that once Pyomo5 expressions were out and GAMS had an expression walker, it would be easy to have the walker simply check everything it comes across in all the active constraints to see if it was a recognized/supported component, i.e. Var, Param, and Expression (correct me if I'm wrong  but I believe it's just those 3). At least for the GAMS writer, this would suffice since it would catch lingering active constraints containing connectors indicating that connectors weren't expanded, and it would allow connectors to still exist on the model as long as they weren't in any active constraints. It would also allow any type of set to exist since GAMS doesn't include the indexing sets anyway, it just writes the variables.

Well, GAMS does have a walker now, so I figure we ought to try it out. You can find the whole walker [here](https://github.com/Pyomo/pyomo/blob/54abf342c14a5f8d5784ce3885759b986bf7f2ef/pyomo/repn/plugins/gams_writer.py#L43), but I believe the important part would be in the visit function, and my plan was to figure out how to make it check for any component that's not one of the 3 above.

My question is, is this the desired fix / behavior? And does anyone know of any edges cases where this would allow something bad to slip through or prohibit something it doesn't need to prevent? @qtothec @blnicho @jsiirola maybe you can think of all your favorite weird components and if they'd present problems.

**Closed** 2018-07-17 22:12 UTC
Labels: IDAES related, pyomo.dae
