### ISSUE TITLE
Interphase of Pyomo with GAMS global solvers cannot read solutions

### ISSUE THREAD

**Issue by caelorza** [Pyomo/pyomo#2573] opened 2022-10-24 03:19 UTC
I tried using GAMS solver, BARON, through Pyomo. I tried using a simple model just to make sure it was working as expected. However, when I run the following code,

```
from pyomo.environ import *

m = ConcreteModel()

m.x = Var([1,2])

m.obj = Objective(expr=-(m.x[1]-2)*(m.x[1]-3)*(m.x[1]-4)*(m.x[1]-6)*(-m.x[2]-1)*(m.x[2]-5), sense=maximize)

m.cons1 = Constraint(expr=m.x[1]<=10)

m.cons2 = Constraint(expr=m.x[1]>=1)

m.cons3 = Constraint(expr=m.x[2]<=7)

m.cons4 = Constraint(expr=m.x[2]>=0)

solver = SolverFactory('gams') 
solvename = 'baron'

sub_options=['GAMS_MODEL.optfile = 1;','\n',
              '$onecho > '+solvename+'.opt \n',
              '$offecho \n']

io_options = dict(
                  add_options=sub_options,
                  )

results = solver.solve(m, tee=True, solver=solvename, io_options=io_options)
```

I get this error:

```
  File C:\ProgramData\Anaconda3\lib\site-packages\pyomo\solvers\plugins\solvers\GAMS.py:1235 in _parse_dat_results
    model_soln[items[0]] = (items[1], items[2])

IndexError: list index out of range
```

GAMS still says that it reached normal completion and the solver says an optimal solution was found, but, for some reason the results cannot be loaded back.

**Comment by jsiirola** [comment] 2022-10-24 03:28
I believe this is a duplicate of #2571, and is a result of recent versions of GAMS changing their output format.

**Closed** 2022-10-26 14:56 UTC
