### ISSUE TITLE
Do not silently fail to perform slicing

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#379] opened 2018-03-03 03:59 UTC
```
from pyomo.environ import *

m = ConcreteModel()
m.s = RangeSet(2)
m.s2 = RangeSet(2)
m.ss = Set(initialize=m.s * m.s2)
m.s3 = RangeSet(3)
m.x = Var(m.ss, m.s3)

print("Case 1")
for var in m.x[:, 3]:
    print(var.name)
    # nothing happens. Expect reasonable error message.

print("Case 2")
for var in m.x[:, :, 3]:
    print(var.name)
    # expected behavior
```

Output:
```
Case 1
Case 2
x[1,2,3]
x[1,1,3]
x[2,1,3]
x[2,2,3]
```

**Comment by Robbybp** [comment] 2020-06-09 18:10
Another example:

```python
from pyomo.environ import *

m = ConcreteModel()

m.time = Set(initialize=[0,1,2,3])
m.space = Set(initialize=[2,4,6,8])
m.comp = Set(initialize=['a','b','c'])

m.v = Var(m.time, m.space, m.comp, initialize=1)

# Would like this to throw an error:
_slice = m.v[:, 1, :, :]
```

**Comment by Robbybp** [comment] 2020-06-09 18:20
An example from `test_indexed_slice.py` seems to indicate that some behavior like this is intended. In the following test, 1 is not valid for the second index of `b[1,:].c`, but the expected behavior seems to be to return an empty slice rather than to raise an error.
```python
    def test_empty_slices(self):
        _slicer = self.m.b[1,:].c[:,1].x
        self.assertIsInstance(_slicer, IndexedComponent_slice)
        ans = [ str(x) for x in _slicer ]
        self.assertEqual( ans, [] )
```
I think all the cases where an index is invalid (extra slice, missing fixed index/slice, or invalid fixed index) should raise exceptions. Thoughts?

**Comment by mrmundt** [comment] 2022-02-22 20:53
@Robbybp - I'm going through old bug reports - do you know if this bug still exists in the current version of Pyomo?

**Comment by Robbybp** [comment] 2022-02-22 21:02
@mmrundt This issue can be closed. To recap, slices with inconsistent dimension now raise exceptions. Slices with an invalid index, but the correct dimension, simply don't return anything. This behavior is intentional as of the discussion in #1492.

**Closed** 2022-02-22 21:02 UTC
Labels: bug, pyomo.core
