### ISSUE TITLE
Add OSQP interface

### ISSUE THREAD

**Issue by amir-hoseyn77** [Pyomo/pyomo#2681] opened 2023-01-03 12:30 UTC
## Summary

Please add some interface for OSQP solver. The OSQP is a good and growing solver for quadratic programming (QP) problems.

### Rationale

The OSQP is a good and growing solver for quadratic programming (QP) problems.<br/>
Also, I think it is not hard to add this interface to pyomo.

**Comment by jonas912** [comment] 2023-01-04 08:52
Seems like this is a duplicate of #1096

**Comment by blnicho** [comment] 2023-01-04 17:50
Closing this as a duplicate

**Closed by blnicho** 2023-01-04 17:50 UTC
Labels: enhancement
