### ISSUE TITLE
Python3.7 breaks import of Pyomo

### ISSUE THREAD

**Issue by Benezivas** [Pyomo/pyomo#645] opened 2018-08-07 13:39 UTC
I just upgraded from Python3.6.6 to Python3.7, after which the Pyomo library import no longer works as expected. From the [changelogs](https://docs.python.org/3/whatsnew/3.7.html) I suspect this error is based on the keyword `async` now being protected.

Using Pyomo version 5.5.0 on Arch Linux.

Module in question:
```
import logging
import timeit
import os
import math

from pyomo.opt import SolverStatus, TerminationCondition
from pyomo.environ import ConcreteModel, RangeSet, Set, Var, Param, Objective, Constraint, NonNegativeReals, NonNegativeIntegers, PercentFraction, Boolean, minimize, SolverFactory, value
[...]
```
Traceback:
```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    from ilp_problem_handler import IlpProblemHandler
  File "/home/path/to/my/Code/src/ilp_problem_handler.py", line 7, in <module>
    from pyomo.environ import ConcreteModel, RangeSet, Set, Var, Param, Objective, Constraint, NonNegativeReals, NonNegativeIntegers, PercentFraction, Boolean, minimize, SolverFactory, value
  File "/usr/lib/python3.7/site-packages/pyomo/environ/__init__.py", line 89, in <module>
    _import_packages()
  File "/usr/lib/python3.7/site-packages/pyomo/environ/__init__.py", line 59, in _import_packages
    _do_import(pname)
  File "/usr/lib/python3.7/site-packages/pyomo/environ/__init__.py", line 16, in _do_import
    importlib.import_module(pkg_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.7/site-packages/pyomo/pysp/__init__.py", line 25, in <module>
    import pyomo.pysp.scenariotree
  File "/usr/lib/python3.7/site-packages/pyomo/pysp/scenariotree/__init__.py", line 18, in <module>
    import pyomo.pysp.scenariotree.manager
  File "/usr/lib/python3.7/site-packages/pyomo/pysp/scenariotree/manager.py", line 969
    async=False,
        ^
SyntaxError: invalid syntax
```

**Comment by qtothec** [comment] 2018-08-07 13:54
Indeed, the `async` keyword is the cause of failure here. A fix already exists on master, but it has not made it into a released version of Pyomo yet. If you need a quick fix, you can install the master version of Pyomo rather than the default release version.

There is already an outstanding issue for the release: https://github.com/Pyomo/pyomo/issues/604.

**Comment by jsiirola** [comment] 2018-08-07 14:26
There is also a branch (pyomo-5.5.1_python-3.7_patch) that will (soon) become a 5.5.1 patch release that is compatible with python 3.7.  The big difference between the branch and master is that master introduces a new expression system that will be released in Pyomo 5.6.

**Comment by jsiirola** [comment] 2018-10-17 14:46
@dmvianna: your comment is orthogonal to this ticket, however, the answer is that Pyomo tracks PyUtilib development closely, so if you are going to work on Pyomo master you will also need PyUtilib master.

**Comment by blnicho** [comment] 2018-11-07 18:56
The patch release to support Python 3.7 is now available so closing this.

**Closed by blnicho** 2018-11-07 18:56 UTC
Labels: bug
