### ISSUE TITLE
Add sinc(x) function

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#323] opened 2018-01-25 06:56 UTC
sinc(x) = 1 if x == 0 else sin(x)/x

While NL files do not support this intrinsic function, it can be supported by adding a variable z and a constraint:

  x*z - sin(x) == 0

**Comment by whart222** [comment] 2018-01-25 06:57
This is the "sampling function" that arises frequently in signal processing applications.  This is perhaps illustrative of a broad class of nonlinear functions that could be added and implicitly represented through transformations of Pyomo expressions.

**Comment by jsiirola** [comment] 2018-01-25 07:33
Why do you want to add this?  First, your example is not the sinc function, as z becomes free at x == 0.  The correct implementation is probably 
```
def sinc(x):
    return Expr_if(IF=x==0, THEN=1, ELSE=sin(x)/x)
```
The problem is that even that may have numerical issues (it is in C1, but not C2: if the ASL evaluates it at 0, the second derivative will be 0).  Maybe there is a better value for the `THEN` clause that would move it into C2?

Making things more confusing, there are two definitions for sinc (the other being `sin(pi*x)/(pi*x)`).  Which do you want to support?

The bigger question is if we want to start implementing a nearly infinite set of functions (much like the GSL?).  I suppose we could, but that is definitely not something we would want imported by `pyomo.environ`.  Maybe you are arguing for a `pyomo.math`?

**Comment by carldlaird** [comment] 2018-01-25 14:30
There are several issues here. the x*z-sin(x) transformation may cause numerical problems for the NLP solver (e.g., at a common initialization of x=0, z=0, but I haven't thought about this too much).

The Expr_if example above is heading in the right direction, but may have trouble because it is doing a exact comparison of a floating point, and sin(x)/x might be poorly behaved numerically for values of x that are very close to zero, but not zero. (Again, we would need to check into it.)

I agree that we should look at a package to add these kinds of functions as needed. However, for them to be useful, we need to ensure the appropriate numerical properties over the valid range.

**Comment by mrmundt** [comment] 2024-01-03 20:19
This functionality could likely be implemented using an `ExternalFunction` or black-box function. Either way, the progression of math libraries in Python and the desire to incur less technical debt has led us to decide to close this issue.

**Closed by mrmundt** 2024-01-03 20:19 UTC
Labels: enhancement, pyomo.core
