### ISSUE TITLE
Can't add to an index connector until owned by a model or block

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#41] opened 2016-09-09 12:40 UTC
I can add stuff to a connector before I assign it to a block, but not to an indexed connector.  If this is expected behavior, I can work with it, but I think it may be a bug.  See this example

``` python
from __future__ import division
from __future__ import print_function

from pyomo.environ import *
from pyomo.core.base.connector import ConnectorExpander

model = ConcreteModel()
model.x = Var(initialize=1, domain=Reals)
model.y = Var(initialize=2, domain=Reals)
c = Connector([1,2])
c[1].add(model.x, name='v')
c[2].add(model.y, name='v')
model.c = c
```

Get this error:

jeslick@pds04:~/base_units> python indexed_connector.py 
Traceback (most recent call last):
  File "indexed_connector.py", line 11, in <module>
    c[1].add(model.x, name='v')
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/connector.py", line 212, in **getitem**
    raise KeyError(msg)
KeyError: "Unknown index '1' in connector IndexedConnector;    Make sure the correct index sets were used.\n    Is the ordering of the indices correct?"
jeslick@pds04:~/base_units>

**Comment by jsiirola** [comment] 2016-11-10 07:37
This is indeed expected behavior.  The problem is that the Connector is not constructed until either it is assigned to a concrete model or it is assigned to an abstract model and the abstract model is constructed.  Theoretically, you could manually construct the connector before adding it to the model by calling `c.construct()`, but in your example, the connector is indexed by a list and not a Pyomo Set.  When you declare components in this way Pyomo will go ahead and create the Sets for you when it is constructing the component.  However, since the connector isn't assigned to a block (or a model), Pyomo doesn't know where to put the implicit set (and therefore doesn't construct it) -- so you will end up getting an error about attempting to iterate over an unconstructed set.

I will leave this ticket open to think about if we can cleanly support constructing components independently of blocks.

**Comment by qtothec** [comment] 2018-01-12 00:49
@eslickj Is this still something that you want to be able to do?

**Comment by eslickj** [comment] 2018-01-12 09:53
I don't think this is causing me any trouble now.

**Comment by jsiirola** [comment] 2018-01-16 02:51
I don't have a good way to handle this, short of reworking all of Set so that SetOf is immediately constructed, which may or may not be a good idea (it certainly goes against how the rest of Pyomo works).

I will close this issue: if @eslickj objects, we can re-open it.

**Closed by jsiirola** 2018-01-16 02:51 UTC
Labels: IDAES related
