### ISSUE TITLE
GAMS writer: invalid syntax caused by -0.0

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#306] opened 2018-01-08 22:41 UTC
@gseastream I have a model in which constraints like `x - -0.0 == 0.0` started to appear. This is invalid GAMS syntax, and so the model failed to solve. I don't have the Pyomo model handy right now, but can send it to you later.

**Comment by whart222** [comment] 2018-01-24 22:00
I don't think we can resolve this until we have a concrete example.  Also, I don't think we should try to resolve this until we merge the new expression system, since that has a different writer for GAMS.

**Comment by jsiirola** [comment] 2018-02-08 16:22
@qtothec: to reiterate @whart222 (and your own comment in #340), can you point us to an example?

**Comment by qtothec** [comment] 2018-02-08 16:30
This turns out to be quite easy:
```
from pyomo.environ import *
m = ConcreteModel()
m.x = Var()
m.y = Var()
m.z = Var()

m.c = Constraint(expr=m.x + m.y == m.z)
m.z.fix(-0.0)
m.o = Objective(expr=m.x)

m.write('/tmp/test.gms')
with open('/tmp/test.gms', 'r') as fin:
    print fin.read()
```

**Comment by whart222** [comment] 2018-04-27 06:49
I have confirmed that this error persists even after resolving PR #272

**Comment by gseastream** [comment] 2018-05-23 20:07
From my brief understanding of the new expression tree walker used by the writer, I have come up with a simple solution that may or may not cover every situation but seems to work. Essentially, if a variable is fixed, wrap it in parentheses, within the `visit` method of the `ToGamsVisitor`:

```python
elif arg.is_variable_type():
    if arg.is_fixed():
        tmp.append("(%s)" % val)
    else:
        tmp.append(val)
```

The problem with the double sign comes up whenever a variable in a sum expression with a negative coefficient is fixed to a negative number. Going off of the example @qtothec gave above, you could even have:

```python
m.c = Constraint(expr=m.x - m.z == 0)
m.z.fix(-1)
```

And you'd get a double negative. This seems to happen just because `z` is replaced with its fixed value independent of what it's coefficient is. Also, we could do more and only add parentheses when necessary if that would be preferable, but doing it always doesn't hurt anything (I believe), and it might be nice to see every variable that was replaced with a fixed value in the model file if someone was inspecting it.

If you all like this solution, let me know and I can create a PR for it.

**Comment by qtothec** [comment] 2018-05-23 20:11
I would be perfectly happy with this fix if it works. Could you add in the example above as a new test as well?

**Comment by gseastream** [comment] 2018-05-25 19:27
@qtothec I'll just throw this comment in here in case you or others find it useful, but to simplify your example from above, to show the output of the model file for yourself, instead of your loop thing you can print it directly to `stdout` in printed format with

```python
import sys
from pyomo.opt import ProblemFormat

m.write(sys.stdout, format=ProblemFormat.gams)
```

The GAMS writer supports writing to file streams. I just discovered this shortcut and wanted to share :) And by discovered I mean I wrote it to do that but it's been a while.

**Closed** 2018-05-26 00:56 UTC
Labels: IDAES related, bug, pyomo.solvers
