### ISSUE TITLE
Singleton Variable shows as None when working with numpy floats

### ISSUE THREAD

**Issue by Franken151** [Pyomo/pyomo#1918] opened 2021-04-09 00:09 UTC
When multiplying a Pyomo singleton variable (one that is not indexed by a set) by a numpy float value, the singleton is interpreted as a None type.  If the variable type is converted to a python float, or if the variable is indexed, all works fine.

This can be problematic in the corner case where we pull a value out of a pandas dataframe, which typically comes out as a numpy.float64 and use that with a pyomo singleton variable.

```
In [1]: from pyomo.environ import *                                                            

In [2]: import numpy as np                                                                     

In [3]: m = ConcreteModel()                                                                    

In [4]: m.x = Var()                                                                            

In [5]: c = np.float64(1.0)                                                                    

In [6]: e = c * m.x                                                                            
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a96d4e6ec665> in <module>
----> 1 e = c * m.x

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [7]: c = float(c)                                                                           

In [8]: e = c * m.x                                                                            

In [9]: m.S = Set(initialize=[1,])                                                             

In [10]: m.y = Var(m.S)                                                                        

In [11]: c = np.float64(1.0)                                                                   

In [12]: e = c * m.y                                                                           

In [13]: # or similarly...                                                                     

In [14]: e = c * m.y[1]                                                                        

```

**Comment by blnicho** [comment] 2021-04-09 18:25
This is a known issue and a duplicate of #31 so I'm going to close this. The current workaround is to cast all numpy floats to native Python floats. The Pyomo team has some ideas for fixing this so hopefully we'll get this resolved soon.

**Closed by blnicho** 2021-04-09 18:25 UTC

**Comment by Galina-O** [comment] 2021-07-29 10:20
Have encountered the same issue and discovered another workaround:
swap the float and the singleton variable in your expression, e.g.
c * m.x
produces the error as described above, but
m.x * c
works fine.
