### ISSUE TITLE
Error when setting variable with units from NumPy float. 

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#3123] opened 2024-02-07 15:46 UTC
## Summary

If you attempt to set a Pyomo variable value from a nonnative numeric type and the variable has units, you will get a confusing message about not being able to convert dimensionless to unit.  It seems the problem is here https://github.com/Pyomo/pyomo/blob/1e259f6c14b0dc45d132214fc4242a002593283b/pyomo/core/base/var.py#L393.  It checks if the value that you are setting the variable to is a native numeric type.  Since NumPy float is not a native numeric type, it is assumed to have units. 

### Steps to reproduce the issue

```python
import pyomo.environ as pyo
import numpy as np

m = pyo.ConcreteModel()
m.x = pyo.Var(units=pyo.units.kg)
x = np.Float(1)
m.x = x
```

### Error Message

```console
File ~\git\pyomo\pyomo\core\base\block.py:634, in _BlockData.__setattr__(self, name, val)
    630             raise
    631         #
    632         # Call the set_value method.
    633         #
--> 634         _set_value(val)
    635 #
    636 # Case 3. Handle setting non-Component attributes
    637 #
   (...)
    656     # return True, this shouldn't be too inefficient.
    657     #
    658     if name == '_parent':

File ~\git\pyomo\pyomo\core\base\var.py:397, in _GeneralVarData.set_value(self, val, skip_validation)
    395     _src_magnitude = value(val)
    396     _src_units = units.get_units(val)
--> 397     val = units.convert_value(
    398         num_value=_src_magnitude,
    399         from_units=_src_units,
    400         to_units=self.parent_component()._units,
    401     )
    402 else:
    403     val = value(val)

File ~\git\pyomo\pyomo\core\base\units_container.py:1384, in PyomoUnitsContainer.convert_value(self, num_value, from_units, to_units)
   1380 to_base_factor, to_base_units = self._pint_registry.get_base_units(
   1381     to_pint_unit, check_nonmult=True
   1382 )
   1383 if from_base_units != to_base_units:
-> 1384     raise UnitsError(
   1385         'Cannot convert %s to %s. Units are not compatible.'
   1386         % (from_units, to_units)
   1387     )
   1389 # convert the values
   1390 from_quantity = num_value * from_pint_unit

UnitsError: Cannot convert dimensionless to kg. Units are not compatible.
```

### Information on your system

Pyomo version: 6.7.1.dev0
Python version: 3.12
Operating system: Windows 
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable):

**Comment by dallan-keylogic** [comment] 2024-02-08 19:34
This appears to be a duplicate of #3100 .

**Comment by mrmundt** [comment] 2024-02-08 19:37
Thanks, @dallan-keylogic . Closing this as a duplicate; please refer to #3100.

**Closed by mrmundt** 2024-02-08 19:37 UTC
Labels: bug
