### ISSUE TITLE
Profile current NL and LP writers to look for opportunities (and improve)

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#1190] opened 2019-11-19 17:01 UTC
I suspect (especially with the NL writer) that there are opportunities to improve performance. This issue suggests that we profile these writers and try to find some low hanging fruit for immediate improvement.

**Comment by whart222** [comment] 2019-11-19 18:55
This looks like a duplicate of #1151, which was also authored by @carldlaird

**Closed** 2019-11-19 18:58 UTC
Labels: performance
