### ISSUE TITLE
Integer Value Error when following example problem.

### ISSUE THREAD

**Issue by jwlevis** [Pyomo/pyomo#1198] opened 2019-11-21 19:19 UTC
I am trying to go through the MindtPy example problem (https://pyomo.readthedocs.io/en/stable/contributed_packages/mindtpy.html) and it does not work. 

Here is my code:

```
from pyomo.environ import *

#Create a simple model
model = ConcreteModel()

model.x = Var(bounds=(1.0,10.0),initialize=5.0)
model.y = Var(within=Binary)

model.c1 = Constraint(expr=(model.x-3.0)**2 <= 50.0*(1-model.y))
model.c2 = Constraint(expr=model.x*log(model.x)+5.0 <= 50.0*(model.y))

model.objective = Objective(expr=model.x, sense=minimize)

#Solve the model using MindtPy
SolverFactory('mindtpy').solve(model, mip_solver='cplex', nlp_solver='ipopt',integer_tolerance=0.1,tee=True) 

model.objective.display()

model.display()

model.pprint()
```
And here is the output:

``` 
INFO: ---Starting MindtPy---
INFO: Original model has 2 constraints (2 nonlinear) and 0 disjunctions, with
    2 variables, of which 1 are binary, 0 are integer, and 1 are continuous.
WARNING: DEPRECATED: The differentiate function in pyomo.core.base.symbolic
    has been deprecated. Please use the differentiate function in
    pyomo.core.expr.  (deprecated in TBD,will be removed in 5.7)
WARNING: DEPRECATED: The differentiate function in pyomo.core.base.symbolic
    has been deprecated. Please use the differentiate function in
    pyomo.core.expr.  (deprecated in TBD,will be removed in 5.7)
INFO: NLP 1: Solve relaxed integrality
INFO: NLP 1: OBJ: 1.0  LB: 1.0  UB: inf
INFO: ---MindtPy Master Iteration 0---
INFO: MIP 1: Solve master problem.
Traceback (most recent call last):

  File "<ipython-input-6-4da2d909ee40>", line 1, in <module>
    runfile('C:/Users/Desktop/untitled0.py', wdir='C:/Users/Desktop')

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Desktop/untitled0.py", line 22, in <module>
    SolverFactory('mindtpy').solve(model, mip_solver='cplex', nlp_solver='ipopt',integer_tolerance=0.1,tee=True)

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\contrib\mindtpy\MindtPy.py", line 373, in solve
    MindtPy_iteration_loop(solve_data, config)

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\contrib\mindtpy\iterate.py", line 30, in MindtPy_iteration_loop
    handle_master_mip_optimal(master_mip, solve_data, config)

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\contrib\mindtpy\mip_solve.py", line 62, in handle_master_mip_optimal
    config)

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\contrib\gdpopt\util.py", line 162, in copy_var_list_values
    v_to.set_value(value(v_from, exception=False))

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\core\base\var.py", line 172, in set_value
    if valid or self._valid_value(val):

  File "C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\core\base\var.py", line 184, in _valid_value
    "domain %s" % (val, type(val), self.domain))

ValueError: Numeric value `0.22709088987977696` (<class 'float'>) is not in domain Binary
```

As you can see the integer tolerance is already up to 0.1, which is pretty high. It will solve if I put the integer tolerance above 0.22709088987977696, but that's not really helpful. I have also tried with GLPK as the LP solver, but the results were exactly the same. 

I am using Surface Pro 4 with Windows 10.

**Comment by qtothec** [comment] 2019-11-21 21:46
This is a duplicate of https://github.com/Pyomo/pyomo/issues/1187

**Closed by qtothec** 2019-11-21 21:46 UTC
