### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by koujiaodahan** [Pyomo/pyomo#1367] opened 2020-03-28 15:58 UTC
```
lib/python2.7/site-packages/pyomo/environ/__init__.py", line 13, in <module>
    import pyomo.core
  File "lib/python2.7/site-packages/pyomo/core/__init__.py", line 10, in <module>
    from pyomo.util.plugin import PluginGlobals
  File "lib/python2.7/site-packages/pyomo/util/__init__.py", line 10, in <module>
    from pyomo.util._task import pyomo_api, PyomoAPIData, PyomoAPIFactory
  File "lib/python2.7/site-packages/pyomo/util/_task.py", line 22, in <module>
    from pyomo.util import plugin
  File "lib/python2.7/site-packages/Pyomo-5.6.10.dev0-py2.7-linux-x86_64.egg/pyomo/__init__.py", line 11, in <module>
    from . import common
  File "lib/python2.7/site-packages/Pyomo-5.6.10.dev0-py2.7-linux-x86_64.egg/pyomo/common/__init__.py", line 13, in <module>
    from . import log
ImportError: cannot import name log
```

**Comment by blnicho** [comment] 2020-03-30 16:54
@koujiaodahan could you give a little more information about the OS you are running on, the versions of Pyomo and PyUtilib, and if you're using Anaconda. Looks like you're using Python 2.7?

I tried to recreate this using Python 2.7 on Linux with the most recent releases and with the master branches of Pyomo/PyUtilib and was unable reproduce the error. It looks like you're working with the master branch of Pyomo, so one thing to try would be deleting all of the `.pyc` files in the Pyomo source code. These can sometimes cause issues when code is moved from one file to another.

**Comment by jsiirola** [comment] 2020-03-31 19:12
In addition to deleting the `.pyc` files, if you are using Pyomo master, you also need to use PyUtilib master.  Please update your PyUtilib install.  PyUtilib recently (in 5.8.0) moved away from using a namespace package to being a regular Python package.  You may want to uninstall PyUtilib completely and re-install it.

**Comment by blnicho** [comment] 2020-04-09 16:12
Closing this. No additional information has been provided and I'm unable to reproduce this locally. @koujiaodahan please reopen if this is still an issue for you.

**Closed by blnicho** 2020-04-09 16:12 UTC
