### ISSUE TITLE
Potential type checking when resolving CUID

### ISSUE THREAD

**Issue by Robbybp** [Pyomo/pyomo#2280] opened 2022-02-04 06:52 UTC
## Summary

Right now, CUIDs can be resolved on a model to "descend into" things that are not Pyomo blocks. For example:
```python
from collections import namedtuple
import pyomo.environ as pyo

VarTuple = namedtuple("VarTuple", ["a"])
m = pyo.ConcreteModel()
m.x = pyo.Var()
m.var_tuple = VarTuple(m.x)
cuid1 = pyo.ComponentUID("var_tuple.a")
comp = m.find_component(cuid1)
print(comp.name)
```
`comp` is the variable `m.x`, and has been correctly identified on the model. This can lead to some slightly confusing behavior, for example:
```python
cuid2 = pyo.ComponentUID(comp)
print(cuid2)
```
Here `cuid2` is different from the `cuid1`, the original identifier used to find the variable, and the variable has no information that can be used to recover the original identifier. This may be the intended behavior, but can be slightly confusing. We could potentially fail gracefully in this case with the following modification to `ComponentUID._resolve_cuid`:
```python
    def _resolve_cuid(self, block):
        obj = block
        prev_obj = block
        for name, idx in self._cids:
            # NOTE: inline import to prevent circular references.
            from pyomo.core.base.block import _BlockData
            if not isinstance(prev_obj, (_BlockData, IndexedComponent_slice)):
                raise TypeError(
                    "Trying to descend into an object of type %s. "
                    "Only BlockData and slice objects are allowed. "
                    % type(prev_obj)
                )
            try:
                if not idx:
                    obj = getattr(obj, name)
                elif len(idx) == 1:
                    obj = getattr(obj, name)[idx[0]]
                else:
                    obj = getattr(obj, name)[idx]
            except KeyError:
                return None
            except AttributeError:
                return None
            except IndexError:
                return None
            prev_obj = obj
        return obj
```

My question is just whether this (CUIDs "descending into" non-Block-like objects) should be allowed.

**Comment by jsiirola** [comment] 2022-02-04 14:56
@Robbybp I don't think that this is something that we should enforce.  CUIDs are only intended to to provide a model-relative unique identifier (the fact that you can generate one from a string is a convenience to the user).  Note that you can also hit the same issue (where two strings would resolve to the same object) even when checking the container type thanks to References.  Unless you are proposing that we generate the "actual" CUID for every component retrieved by string and then complain anytime the string representation of the CUID differs from the string used to generate it?

**Comment by Robbybp** [comment] 2022-02-04 17:35
Yeah, I think I also lean against enforcing this at this point. I mostly just wanted to document some potentially confusing behavior.

**Comment by jsiirola** [comment] 2022-02-08 18:52
Given our discussion, I am going to close this issue as a "wontfix", as this is expected behavior that doesn't have a feasible workaround.

**Closed by jsiirola** 2022-02-08 18:52 UTC
Labels: enhancement, wontfix
