### ISSUE TITLE
Numpy logic error in 5.5

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#611] opened 2018-07-16 15:54 UTC
Anna ran across a bug this morning.

In Pyomo 5.5, the following code will cause a model to be constructed with `numpy.ndarray` objects that results in an empty model (?) being sent to the solver. Even though IPOPT will report `Optimal solution` here, the initial model values will remain unchanged (`c_1 = c_2 = 1` rather than the optimal value of `c_1 = c_2 = 0.5`). This is not due to a non-convexity.

Luckily, in the new expression system, an exception is raised because `numpy.ndarray` does not have an expected `is_expression_type` attribute during expression generation.

If we plan to release 5.5.1, we should address this issue.

## Model
```
import numpy as np
from pyomo.environ import *


def run_model():
    samples = 10
    c1 = .5
    c2 = .5

    model = ConcreteModel()
    model.i = RangeSet(samples)

    def init_x(model, i):
        return np.random.rand(1)

    def init_y(model, i):
        return c1 * (model.x[i]**2) + c2 * model.x[i]

    model.x = Param(model.i, initialize=init_x)
    model.y = Param(model.i, initialize=init_y)
    model.c_1 = Var(within=Reals, initialize=1)
    model.c_2 = Var(within=Reals, initialize=1)

    model.error = Objective(
        # Sum squared error of quadratic fit
        expr=sum(((model.c_1 * (model.x[i]**2) + model.c_2 * model.x[i])
                  - model.y[i]
                  )**2
                 for i in model.i))

    SolverFactory('ipopt').solve(model, tee=True)
    model.display()


if __name__ == '__main__':
    run_model()
```

## Pyomo 5.5 output
```
EXIT: Optimal Solution Found.
Model unknown

  Variables:
    c_1 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :   1.0 :  None : False : False :  Reals
    c_2 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :   1.0 :  None : False : False :  Reals

  Objectives:
    error : Size=1, Index=None, Active=True
        Key  : Active : Value
        None :   True : [3.47962527]

  Constraints:
    None
```

## Pyomo master (commit https://github.com/Pyomo/pyomo/commit/ab7868db53fe3bdaa1ad66ab65e3c9795ebaefa0)
```
ERROR: Rule failed when generating expression for objective error:
    AttributeError: 'numpy.ndarray' object has no attribute
    'is_expression_type'
ERROR: Constructing component 'error' from data=None failed: AttributeError:
    'numpy.ndarray' object has no attribute 'is_expression_type'
Traceback (most recent call last):
  File "..\numpy_error_lists.py", line 25, in <module>
    model.error=Objective(rule=error_rule,sense=minimize)
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\base\block.py", line 538, in __setattr__
    self.add_component(name, val)
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\base\block.py", line 978, in add_component
    val.construct(data)
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\base\objective.py", line 340, in construct
    tmp = _init_rule(_self_parent)
  File "..\numpy_error_lists.py", line 24, in error_rule
    return sum(((model.c_1*(model.x[i]**2)+model.c_2*model.x[i])-model.y[i])**2 for i in model.i)
  File "..\numpy_error_lists.py", line 24, in <genexpr>
    return sum(((model.c_1*(model.x[i]**2)+model.c_2*model.x[i])-model.y[i])**2 for i in model.i)
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\expr\numvalue.py", line 770, in __mul__
    return _generate_mul_expression(_mul,self,other)
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\expr\expr_pyomo5.py", line 3060, in _generate_mul_expression
    if not (_other.__class__ in native_types or _other.is_expression_type()):
AttributeError: 'numpy.ndarray' object has no attribute 'is_expression_type'
```

**Comment by whart222** [comment] 2018-07-16 15:59
Am I right that the problem is in Param initialization?  It sounds like the np.ndarray is being used as an object in an expression tree, rather than being indexed to initialize all of the Param values separately.  Yes?

**Comment by qtothec** [comment] 2018-07-16 16:00
Yes, wrapping the return values from the `Param` rule functions in `float` resolved the issue, i.e. `return float(np.random.rand(1))`.

**Comment by jsiirola** [comment] 2018-07-16 16:37
I cannot reproduce the Ipopt result on either 5.5 or 5.4.3.  In both cases, I get:
```
bad line 16 of /home/jdsiiro/Research/pyomo/tmp/tmpnDUAr9.pyomo.nl: narray([-0.93759936])
terminate called after throwing an instance of 'Ipopt::TNLP::INVALID_TNLP'
Ipopt 3.12.4:
Cannot open .nl file
ERROR: Solver (ipopt) returned non-zero return code (-6)
ERROR: See the solver log above for diagnostic information.
Traceback (most recent call last):
  File "anna-param-bug.py", line 37, in <module>
    run_model()
  File "anna-param-bug.py", line 32, in run_model
    SolverFactory('ipopt').solve(model, tee=True)
  File "/projects/sems/install/rhel6-x86_64/pyomo/tpl/pyomo/5.5.0/lib/python2.7/site-packages/pyomo/opt/base/solvers.py", line 626, in solve
    "Solver (%s) did not exit normally" % self.name)
pyutilib.common._exceptions.ApplicationError: Solver (ipopt) did not exit normally
```
...That said, this is definitely a bug.  I don't think spending too much time fixing the 5.5.x release is warranted (it is likely to not be an easy fix).  But we should get it resolved on master.

**Comment by qtothec** [comment] 2018-07-16 16:40
Odd. Might have to do with py2.7 vs py3.6?

This isn't as troubling an issue on master because the new expression system raises the exception earlier.

**Comment by carldlaird** [comment] 2018-07-16 17:14
Should Pyomo do the wrapping? (i.e., we cast the return value from the rule to a float?)

**Comment by jsiirola** [comment] 2018-07-16 17:29
Yes.  I believe that the correct behavior is to leave the native type in the expression tree, but the writer should be sure to case the "constants" it emits to a float before converting them to a string.  This might be as simple of a fix as changing a `%s` to a `%0.17g`. (Although there is some debate over the correct value for the number of digits of precision: 16 is the standard, but when converting from double to string and back to double, 17 appears to be more stable).

**Comment by tomaszG247** [comment] 2021-07-09 14:22
I was trying to initialize an indexed parameter with an np.array 

`param = aml.Param(range(0, N-1), mutable=True, initialize = np.ones(N))`

and got the following

```
File "c:\myfile.py", line 1510, in solveProblem
    results = solver.solve(self._pyomo_problem, tee=show_solver_output)
  File "C:\Users\TGi\AppData\Local\Continuum\anaconda3\envs\pentagon\lib\site-packages\pyomo\opt\base\solvers.py", line 569, in solve
    self._presolve(*args, **kwds)
  File "C:\Users\TGi\AppData\Local\Continuum\anaconda3\envs\pentagon\lib\site-packages\pyomo\solvers\plugins\solvers\CBCplugin.py", line 289, in _presolve
    super(CBCSHELL, self)._presolve(*args, **kwds)
  File "C:\Users\TGi\AppData\Local\Continuum\anaconda3\envs\pentagon\lib\site-packages\pyomo\opt\solver\shellcmd.py", line 200, in _presolve
    OptSolver._presolve(self, *args, **kwds)
  File "C:\Users\TGi\AppData\Local\Continuum\anaconda3\envs\pentagon\lib\site-packages\pyomo\opt\base\solvers.py", line 669, in _presolve
    **kwds)
  File "C:\Users\TGi\AppData\Local\Continuum\anaconda3\envs\pentagon\lib\site-packages\pyomo\opt\base\solvers.py", line 721, in _convert_problem
    **kwds)
  File "C:\Users\TGi\AppData\Local\Continuum\anaconda3\envs\pentagon\lib\site-packages\pyomo\opt\base\convert.py", line 100, in convert_problem
    problem_files, symbol_map = converter.apply(*tmp, **tmpkw)
  File "C:\Users\TGi\AppData\Local\Continuum\anaconda3\envs\pentagon\lib\site-packages\pyomo\solvers\plugins\converter\model.py", line 81, in apply
    io_options=io_options)
  File "C:\Users\TGi\AppData\Local\Continuum\anaconda3\envs\pentagon\lib\site-packages\pyomo\core\base\block.py", line 1812, in write
    io_options)
  File "pyomo\repn\plugins\cpxlp.pyx", line 157, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp.__call__
  File "pyomo\repn\plugins\cpxlp.pyx", line 158, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp.__call__
  File "pyomo\repn\plugins\cpxlp.pyx", line 159, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp.__call__
  File "pyomo\repn\plugins\cpxlp.pyx", line 510, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp._print_model_LP
  File "pyomo\repn\standard_repn.pyx", line 347, in pyomo.repn.standard_repn.generate_standard_repn
  File "pyomo\repn\standard_repn.pyx", line 973, in pyomo.repn.standard_repn._generate_standard_repn
AttributeError: 'numpy.ndarray' object has no attribute 'is_constant'
```
Is this the same issue ?

**Comment by jsiirola** [comment] 2021-07-09 15:17
@tomaszG247: no, but your issue is known and is likely to be resolved in main here in a week or so (we are in the middle of a push to improve numpy integration).  The workaround is to convert the numpy ndarray to a dict (e.g., with something like `dict(numpy.ndenumerate(data))`)

**Comment by tomaszG247** [comment] 2021-07-12 06:47
thank you

**Closed** 2021-08-12 18:28 UTC
Labels: bug, pyomo.core, pyomo.solvers
