### ISSUE TITLE
Default mutable Param value

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#300] opened 2018-01-03 07:08 UTC
The following used to work:

```python
m = ConcreteModel()
model.p = Param(mutable=True)
assert model.p.value == None
```

This now results in an error when `model.p.value` is accessed with the message "The Param value is undefined and no default value is specified”. I’m not here to fight that behavior, but I do often make use of the ability to count on mutable parameters having a default value of `None`. It is a very natural starting state. There is also some critical behavior in PySP that relies on this functionality, and this issue is currently holding up a merge of the PySP dev branch into master. 

My naive attempt to get around this issue was to change the Param declarations to look something like

```python
model.p = Param(mutable=True, default=None)
# or
model.p = Param(mutable=True, initialize=None)
```

But this actually doesn’t fix anything because the value of `None` just gets interpreted as “not set”.

What do folks think about changing the semantics of Param so that explicitly setting keywords like "default" and "initialize" to `None` gets interpreted differently from not using the keywords at all? There are various ways this can be implemented. E.g.,

```python
_noarg = object()
def f(x=_noarg):
    if x is not _noarg:
        ...
```
or
```python
def f(**kwds):
    if 'x' in kwds:
        ...
```

**Comment by whart222** [comment] 2018-01-03 15:37
Alternatively, is there a reason to not allow the value 'None' to indicate 'undefined'?

I can think of other cases where we want to test if a variable has a defined value.  If we don't allow the value of 'None', then we need a method like 'has_value()' or 'is_defined()' so users don't have to use a try/catch block.

**Comment by DLWoodruff** [comment] 2018-01-03 15:45
I think you have it exactly right:
- It is not clear that the value should be None by default, but
- it does make a lot of sense to support initialize = None
   Dave


On Tue, Jan 2, 2018 at 11:08 PM, Gabriel Hackebeil <notifications@github.com

**Comment by jwatsonnm** [comment] 2018-01-03 17:10
Well, if you're not going to fight that behavior, I will. It seems crazy to not allow a ".value" access on a mutable parameter. So we can never programmatically interrogate whether it has a valid value, and will rather always get (and have to catch) an exception? That's beyond ugly and will ultimately confuse end-users. And, for example, we don't do this for variables - so at a minimum the interfaces are inconsistent. 

A quick question: When exactly did this behavior get changed? Presumably quite recently?

Seems like Bill agrees with me, and Bill and I disagree with Dave I(albeit mildly) - I think the value of a mutable parameter should default, as do variables, to None. It also seems more pythonic.

But I think we are all in agreement that it does make sense to support initialize=None.

**Comment by ghackebeil** [comment] 2018-01-03 20:55
I think this change came in on the constraint-default-fix branch merge through PR #133 a few days ago.

It looks like the more fundamental design change is that now accessing `.value` always raises an exception when the value stored is `None`, no matter how the parameter was initialized (e.g., accessing `p.value` immediately after executing `p.value = None` will result in the same error).

In the meantime, I'm going to work around this in PySP by accessing `._value`; thus, avoiding the getter method that does this check.

**Comment by jsiirola** [comment] 2018-01-03 20:56
The behavior changed when #133 was merged in.  The reason is that #133 is far more consistent between Indexed and Scalar component behavior.  The fact that
```python
m = ConcreteModel()
model.p = Param(mutable=True)
assert model.p.value == None
```
worked in the past was because scalar Params did not correctly handle certain error checking.  In this example, you are declaring a mutable param `p`, but not initializing it and not specifying a default value.  Therefore, attempting to *retrieve* a value should absolutely raise an exception.  The justification for this behavior is a sparse mutable Param.  I would definitely expect the following to throw an exception:
```python
m.q = Param([1,2,3], initialize={1:10,3:30}, mutable=True)
assert m.q[2].value == #???
```
After all, if `q` were a dictionary, you would get a KeyError.

The point is that there should be a distinction between checking if the value is *defined* and checking the value.  For @ghackebeil's original use case, you should check if the index is present:
```python
>>> m = ConcreteModel()
>>> m.p = Param(mutable=True)
>>> m.q = Param([1,2,3], initialize={1:10,3:30}, mutable=True)
>>> 1 in m.q
True
>>> 2 in m.2
False
>>> None in m.p
False
>>> m.p = None
>>> None in m.p
True
```
I realize that this will cause some consternation, as it is not exactly clear why we are checking for `None` (e.g., this has caused @qtothec confusion in the past).  Maybe we should consider an alternative thing to use as the index for a scalar IndexedComponent (`()`???), but that is a separate discussion.

As to @ghackebeil's proposal, I am not opposed to changing the value to use to indicate "value not set" for `default` and `initialize` keywords to something other than `None` **IF** we decide that `None` is a valid value for Params.  I am inclined to allow non-numeric values to be stored in Params (we already allow `str`), so using that logic, I would support `None` as well.  If we are going to implement it, I would prefer using:
```python
class _ValueNotProvided(object):
    pass
class _ParamData(ComponentData):
    def __init__( [...], default=_ValueNotProvided, [...]):
        self.default_value = default
    #...
    def f(self):
        if self.default_value is _ValueNotProvided:
            raise #...
```
The reason to use a `type` and not an `object` instance is so that when the component is pickled / cloned, the _ValueNotProvided remains a proper singleton.  (Unless you add special processing `_noarg` would be copied and the `is`/`is not` tests would all fail, and I believe that we should avoid `**kwds` wherever possible for core features because of how it obscures the API.)

**Comment by jsiirola** [comment] 2018-01-03 21:01
@ghackebeil:  Please work around using `None in m.p` instead of accessing the non-public attribute.

**Comment by ghackebeil** [comment] 2018-01-03 21:21
Besides being very confusing, `None in m.p` is not equivalent to "p has no value" or "p has value None":

```python
m = ConcreteModel()

m.p = Param(mutable=True)
# an assignment
m.p.value = None
None in m.p # -> True

m.q = Param(mutable=True)
# an attempted read
try:
    m.q.value
except:
    pass
None in m.q # -> True
```


The same issues occurs for the indexed case.

**Comment by jsiirola** [comment] 2018-01-03 21:26
OK - that is a bug.  I am working on a fix and will have a PR in shortly.

**Comment by jsiirola** [comment] 2018-01-04 00:10
@ghackebeil: among other things, note that PR #301 fixes (and adds tests for) the `None not in m.p` bug you point out above.

**Comment by jwatsonnm** [comment] 2018-01-04 00:53
I disagree with the assertion that 

m = ConcreteModel()
model.p = Param(mutable=True)
assert model.p.value == None

should absolutely yield an exception. As with a Var, None is a completely reasonable default value for the value attribute, should the constructor not provide an alternative. This imposes unexpected heavy-weight behavior on what should be a light-weight getter activity.

And we can't quite treat the example below as analogous to dictionary access:

m = ConcreteModel()
m.q = Param([1,2,3], initialize={1:10,3:30}, mutable=True)
 
In this case, I would expect m.q[2] to return None, as you've already said that the keys 1, 2, and 3 are defined. And one index value just happens to not be initialized (yet). You should most definitely not get a key error when indexing with 2. After all, if you say

m.v = Var([1,2,3], within=NonNegativeReals)

you don't have the issue with value or index access.

**Comment by whart222** [comment] 2018-01-04 04:46
Let me contradict myself.  For some reason I thought this issue was about Var, which is a different beast.

By design, Param and Var act differently.  Like virtually all components in Pyomo, the index set for Param defines feasible index values, but the component itself is sparsely defined.  For example,

M = ConcreteModel()
M.A = Set(initialize=[1,2,3])
M.x = Var(M.A)
M.p = Param(M.A, initialize={1:10, 3:30})
def _rule(M, a):
   if a == 2:
      return Constraint.Skip
   return M.x <= a
M.c = Constraint(M.A, rule=_rule)

Both M.p and M.c are sparsely defined, so it makes sense to return an error when referencing M.p[2] and M.c[2].  M.x is a variable, which by default is dense.  So M.x[2] is defined.

If you want a dense parameter, you can define a default value, such as:

  M.q = Param(M.A, default=0)

Then, M.q[2] is defined.

NOTE:  This semantics and behavior is consistent with how a Python dictionary works, so I don't know why it's a surprise that M.p[2] would return an exception.  (I tried earlier to convince everyone that it made sense to treat variables in a similarly sparse manner, but failed! {sigh})

I think the right thing to do is to (a) keep the current behavior of raising an exception if the index is not used, and (b) add a method to access values with a default.  For example, we could mimic Python dict and support:

M.p.get(2, None)     # Get the value of index 2, and return None if it's not defined

or 

M.p.get_value(2, None)     # We might want a more explicitly named 'get' method.


I think it's confusing to allow initialization with None values, and it creates an asymmetry with native Python data types.  We've struggled with such asymmetries in the past, since they create situations where the logic with Pyomo data objects differs from a user's experience with Python native data.

NOTE:  There could be a case made to treat singleton param values differently.  But even so it seems really unintuitive to me to initialize parameter values with None.

**Closed** 2018-01-24 22:43 UTC
