### ISSUE TITLE
Clone breaks direct variable domain comparison

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#165] opened 2017-06-14 16:42 UTC
Trying `v.domain is Binary` or `v.domain == Binary` gives the wrong answer with a cloned model. `v.is_binary()` gives the correct result, but users may not realize that they need to do so.

**Input:**
```
from pyomo.environ import (ConcreteModel, Var, Binary)
from pprint import pprint

m = ConcreteModel()
m.x = Var()
m.y = Var(domain=Binary)

m2 = m.clone()
binaries = [v for v in m2.component_data_objects(
            ctype=Var, descend_into=True)
            if v.domain is Binary and not v.fixed]
pprint(binaries)
any_var = [v for v in m2.component_data_objects(ctype=Var, descend_into=True)]
for v in any_var:
    print(str(v.domain), v.domain is Binary, v.domain == Binary)
pprint(any_var)
```
**Output:**
```
[]
('Reals', False, False)
('Binary', False, False)
[<pyomo.core.base.var.SimpleVar object at 0x7f5afec68e60>,
 <pyomo.core.base.var.SimpleVar object at 0x7f5afec68ed8>]
```

**Comment by ghackebeil** [comment] 2017-06-14 21:20
This is definitely unintended behavior. Thanks for reporting it.

A few things:

 1. When I added the `is_binary()`, etc. helper methods, it was more about cleaning up code across the various solver interfaces for checking domains. I didn't realize they would also get around this problem.

 2. I'm sure there are a few ways to fix this (e.g., hacks to setstate on Var, hacks to make the domain sets "persistent" objects, or making the domain sets classes rather than instances of a class), but without getting into that, let me recommend that you try to stick with the `is_binary()`, `is_integer()`, `is_discrete()`, and `is_continuous()` methods where possible. Ticket #86 discusses a proposal I am making to clean up the semantics of variable domains. In that ticket I am proposing we remove the `.domain` attribute (or only allow assigning to it), and simply provide a `.domain_type` attribute that is always `RealSet` or `IntegerSet` (which would not have the issue you reported because they are classes). There hasn't been much feedback on this, but it is fully implemented and tested in pyomo.kernel. If you stick with those helper methods, your code will still run whether or not we move this change into the AML interface in the future.

**Comment by jsiirola** [comment] 2018-01-30 17:18
The root cause is that the "special" Sets implemented in `pyomo/core/kernel/set_types.py` are duck-typed Component objects (i.e., they are *not* `Set` objects).  If they inherited from Component, then `clone()` wouldn't duplicate them and this issue would be resolved.

**Closed** 2019-09-24 18:42 UTC
Labels: IDAES related, bug, pyomo.core
