### ISSUE TITLE
ExternalFunction with fixed variables not working

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#16] opened 2016-08-05 20:04 UTC
I am able to use ExternalFunction ok in Pyomo, but the expressions cannot be evaluated in Python.  If the arguments to the function happen to be fixed, when the problem is sent to the solver, I think Pyomo tries to evaluate the function with fixed arguments and turn it into a constant.  This causes an error like ExternalFunction cannot be evaluated by Python.

I'm not able to get the exact error message right now, but I can add details (even a sample problem) if needed.

**Comment by whart222** [comment] 2016-08-05 20:08
A sample problem with an error message would be very helpful.

**Comment by eslickj** [comment] 2016-08-08 12:20
I put an example here https://github.com/eslickj/bug_examples/tree/master/fixed_vars_in_external.  You can see if you don't fix T and P it works fine.  If you do fix T and P you get the error at the end.  I included a rough makefile to compile the ExternalFunction.  You will probably need to edit it so it will find the ASL files.  I don't know much, but I can try to help if you have any trouble compiling it.  I tried to keep it really simple so the source of the error should be clear, but let me know if you need more information.

Error Message:

jeslick@pds04:~/ext_error> python model.py
ERROR: Constructing component 'Veq' from data=None failed:
	NotImplementedError: General external functions can not be evaluated within Python.
Traceback (most recent call last):
  File "model.py", line 27, in <module>
    main()
  File "model.py", line 19, in main
    model.Veq = Constraint(expr=V==Vfunc(T,P))
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/block.py", line 483, in __setattr__
    self.add_component(name, val)
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/block.py", line 849, in add_component
    val.construct(data)
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/constraint.py", line 711, in construct
    cdata = self._check_skip_add(None, tmp, condata=self)
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/constraint.py", line 897, in _check_skip_add
    condata.set_value(expr)
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/constraint.py", line 1047, in set_value
    return _GeneralConstraintData.set_value(self, expr)
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/constraint.py", line 562, in set_value
    val = self._lower()
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/expr_coopr3.py", line 204, in __call__
    exception=exception))
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/expr_coopr3.py", line 274, in _apply_operation
    return self._fcn.evaluate(values)
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/external.py", line 68, in evaluate
    "General external functions can not be evaluated within Python." )
NotImplementedError: General external functions can not be evaluated within Python.

**Comment by ghackebeil** [comment] 2016-08-08 12:56
Thanks for that great example. I was able to reproduce everything.

I think I understand what the problem is. When Pyomo sees that the bound expression for the constraint can be simplified into a constant, it attempts to evaluate it. That way you get a linear constraint in the NL file, rather than a nonlinear one.

I think we probably can support evaluation of external C functions by using the cffi module. If you wouldn’t mind opening an issue at the Pyomo GitHub page, I’ll see if I can add in a quick fix for this.

Gabe

P.S. With your permission, I would like adapt your code into an example for using external functions with our ASL interface, and add it to the PyomoGallery on GitHub.

**Comment by ghackebeil** [comment] 2016-08-08 13:06
Sorry, I wasn't being very observant here. Didn't realize I was replying to a GitHub issue in my email client.

**Comment by eslickj** [comment] 2016-08-08 13:11
That's okay, but I was confused about where I should be filing this new gtihub issue.

I would be happy to have you use my code as the basis of and example.

**Comment by ghackebeil** [comment] 2016-08-09 01:28
I've [forked](https://github.com/ghackebeil/bug_examples) your example and shown how you can use some cffi magic to make the ExternalFunction callable from Python. The steps are:

 1. Install cffi (pip install cffi)
 2. Make sure that cffi is compiled with the same compiler used to build the .so
 3. Create a dummy wrapper C function that uses return and argument types that cffi understands (e.g., double, rather than ASL typedefs), but calls the original function that ASL will use.
 4. Override the "evaluate" method on the ExternalFunction instance by assigning it a function that calls the wrapper C function using cffi.

I've broken apart these changes into a few commits on my fork so it's easier to follow. This feels more like a workaround to me, but I can't think of any other way to make this work. Maybe @jsiirola can come up with something.

**Comment by ghackebeil** [comment] 2016-08-09 01:48
Also, note that another approach would be to "fix" the variables simply by setting their upper and lower bounds to be equal (rather than calling var.fix()). They will remain as a variable in the NL file, but some solvers, Ipopt in particular, will do some extra preprocessing to to eliminate these variables from the problem (see the fixed_variable_treatment Ipopt option, ipopt --print-options). Your external function might still be called with each Ipopt iteration using this second approach, but maybe that is okay if the function call is cheap.

**Closed** 2016-08-11 06:03 UTC

**Comment by jsiirola** [comment] 2016-08-11 06:17
37ed7f7 fixes our AMPL external function interface to support directly calling out to the library from within Python.  

@ghackebeil: note that this uses the Python `ctypes` library, so does not add any additional dependencies to Pyomo.  It is a pretty generic interface, although it does not completely populate the AmplExports data structure.  This may get us in trouble if the external library relies on any of the function pointers that are defined in that structure (e.g., for the AMPL `stdio` reimplementation) -- currently they are all NULL pointers.
