### ISSUE TITLE
Weird bugs and errors when checking list containment

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#643] opened 2018-08-06 16:16 UTC
Weird things happen when I try to check if an indexed variable is in a list. Consider the following:

```
>>> m.s = RangeSet(5)
>>> m.x = Var(m.s)
>>> m.x in [m.x]
True
>>> m.x in [m.x[2]]
Traceback (most recent call last):
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 2869, in _process_arg
    if obj.is_parameter_type() and not obj._component()._mutable and obj._constructed:
AttributeError: 'IndexedVar' object has no attribute 'is_parameter_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/numvalue.py", line 744, in __eq__
    return _generate_relational_expression(_eq, self, other)
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 3241, in _generate_relational_expression
    rhs = _process_arg(rhs)
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 2883, in _process_arg
    % (obj.name, ) )
TypeError: Argument for expression is an indexed numeric value
specified without an index:
	x
Is this value defined over an index that you did not specify?
>>> m.x[2] in [m.x[2]]
True
>>> m.x[2] in [m.x[2], m.x[3]]
True
>>> m.x[2] in [m.x[1], m.x[2], m.x[3]]
ERROR: evaluating object as numeric value: x[2]
        (object: <class 'pyomo.core.base.var._GeneralVarData'>)
    No value for uninitialized NumericValue object x[2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 2110, in __nonzero__
    return bool(self())
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 1314, in __call__
    return evaluate_expression(self, exception)
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 881, in evaluate_expression
    return visitor.dfs_postorder_stack(exp)
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 460, in dfs_postorder_stack
    flag, value = self.visiting_potential_leaf(_sub)
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 801, in visiting_potential_leaf
    return True, value(node)
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/numvalue.py", line 225, in value
    % (obj.name,))
ValueError: No value for uninitialized NumericValue object x[2]
>>> m.x.fix(5)
>>> m.x in [m.x[2]]
Traceback (most recent call last):
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 2869, in _process_arg
    if obj.is_parameter_type() and not obj._component()._mutable and obj._constructed:
AttributeError: 'IndexedVar' object has no attribute 'is_parameter_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/numvalue.py", line 744, in __eq__
    return _generate_relational_expression(_eq, self, other)
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 3241, in _generate_relational_expression
    rhs = _process_arg(rhs)
  File "/home/gseastr/envs/pyomo/pyomo/core/expr/expr_pyomo5.py", line 2883, in _process_arg
    % (obj.name, ) )
TypeError: Argument for expression is an indexed numeric value
specified without an index:
	x
Is this value defined over an index that you did not specify?
>>> m.x[2] in [m.x[1], m.x[2], m.x[3]]
True
```

**Comment by qtothec** [comment] 2018-08-06 16:19
Variables are not hashable. When you attempt to perform equality comparison (with `in`), the result is expression generation. Try `m.x[2] in ComponentSet([m.x[1], m.x[2], m.x[3]])`.

**Comment by qtothec** [comment] 2018-08-06 16:28
It checks both, apparently: https://docs.python.org/3/reference/expressions.html#membership-test-details

**Comment by gseastream** [comment] 2018-08-06 16:51
Then do we want to pursue a better error message? I actually don't know if that's even possible. Or perhaps this is actually a good error message since it's correct that it can't evaluate the uninitialized variable.

Regardless, something I learned from this is that `in` really shouldn't be used for variables with list containment since if you have `m.x` and `m.y` with equal values, `m.y in [m.x]` will return True.

**Comment by qtothec** [comment] 2018-08-06 16:57
Correct. Might be worth adding a tip to the documentation about this, but I don't personally plan to pursue this one much further at this time.

**Comment by qtothec** [comment] 2018-08-07 15:57
@gseastream Can we close this, or do we want to follow up with it?

**Comment by jsiirola** [comment] 2018-08-07 16:03
I'd like to leave this open for a while.  I suspect that we should be able to either fix this straightaway or at least produce a better error message.  There are a couple things going on here:
  - there are errors in pyomo5 expression assumptions around input arguments that should be refined / fixed (the cause of the exception initially reported)
  - some of this is running afoul of the (now deprecated) "`a <= b <= c`" syntax.

**Comment by gseastream** [comment] 2018-08-07 16:10
@jsiirola I'm still not sure what we can do to produce a better error message, unless you are proposing we change the errors that arise out of attempting to boolean evaluate an expression with uninitialized variables. That is the core of the issue here, since python's `in` operator is trying to check if `a == b` when checking for containment (if `is` fails first), which is exactly how our expression system represents an EqualityExpression.

**Comment by mrmundt** [comment] 2024-01-03 21:18
This issue is sufficiently outdated / not of concern for us to close it.

**Closed by mrmundt** 2024-01-03 21:18 UTC
Labels: pyomo.core
