### ISSUE TITLE
EXIT: Restoration Failed!

### ISSUE THREAD

**Issue by quan12jiale** [Pyomo/pyomo#790] opened 2018-12-21 03:41 UTC
The code runs as follows:
Restoration phase converged to a feasible point that is
unacceptable to the filter for the original problem.
Restoration phase in the restoration phase failed.

                                   (scaled)                 (unscaled)
Objective...............:  5.5298756902120821e+007   5.5298756902120821e+007
Dual infeasibility......:  9.9999999998275313e-001   9.9999999998275313e-001
...
Overall NLP error.......:  9.9999999998275313e-001   9.9999999998275313e-001

In fact, the objective function calculated at this time can meet my requirements, but Dual infeasibility and Overall NLP error do not meet the requirements of pyomo.
How to get the value of each variable in this case?
The variable I am referring to is defined as such: model.ec=Var()

**Comment by jsiirola** [comment] 2018-12-21 17:20
Closing as a duplicate of #789.  I am putting additional comments there, as that issue contains more context.

**Closed by jsiirola** 2018-12-21 17:20 UTC
