### ISSUE TITLE
parallel optimization architecture  and optimizers for deep learning

### ISSUE THREAD

**Issue by shuruiz** [Pyomo/pyomo#739] opened 2018-11-03 04:59 UTC
Is there any plan to develop parallel optimization algorithm/architecture or optimizer interface for deep learning frameworks like pytorch and tensorflow? If so, I will be glad to help.

**Comment by whart222** [comment] 2018-11-07 04:51
Can you be more specific about the types of problems that you cannot already handle in pytorch and tensorflow? Or are you suggestion an alternative?

I think it would be very interesting to develop a framework that is complementary to pytorch and/or tensorflow.  Though that would require a direct solver interface that Pyomo doesn't support right now.  I've been prototyping such an interface in a separate repository, though.

**Comment by blnicho** [comment] 2019-11-26 15:44
There hasn't been any response to Bill's questions in over a year so closing this.

**Closed by blnicho** 2019-11-26 15:44 UTC
Labels: enhancement, question

**Comment by JTaets** [comment] 2020-11-29 16:04
I would also like to use pyomo together with neural networks (pytorch), has this interface been implemented yet?

**Comment by wangyexiang** [comment] 2021-09-01 01:56
> I would also like to use pyomo together with neural networks (pytorch), has this direct solver interface been implemented yet?

Dear sir, do you solve this issue?

**Comment by shuruiz** [comment] 2021-09-01 02:59
Sorry for the late response guys. I was super busy in the past few years regarding my research. I can start working on the issue if this is still unresolved. Can you please specify your problems in detail? @JTaets @wangyexiang @whart222

**Comment by wangyexiang** [comment] 2021-09-03 12:07
Dear sir，the issue is here:[https://github.com/Pyomo/pyomo/issues/2113](url)@ shuruiz
